### ISSUE TITLE
Single product page Add to cart (Product details not added to cart)

### ISSUE THREAD

**Issue by forinda** [eucossa-2022-sem2-web2-project/react-frontend-service-2022-s1#36]
**Describe the bug**
Adding product to cart and on preview of the shopping cart the shopping cart price value is `NAN` 

**To Reproduce**
- On the Homepage Click on the single product to navigate to tsingle product display page
- Click on add to cart 
- The product gets added but price is `nan`
- If you go to categories page and add items to cart it does. If you add another product from the single product page then no item is added to the cart at all. 
- Product details are also not added to the cart as the product name is not displayed
- Product cannot clear itself from the cart

**Expected behavior**
The product added to cart should update the price and should display the amount it costs to purchase a product.
if items exist in the cart the new product shuld just update in the cart and if it does not exist it should slot in
![Screenshot 2022-10-18 23:54:28](https://user-images.githubusercontent.com/55891685/196542849-bfc40956-8709-496c-b5e1-e8e3c856fa98.png)

**Screenshots**
![Screenshot 2022-10-18 23:47:04](https://user-images.githubusercontent.com/55891685/196541704-501f7add-a9e9-48c9-b48b-a90a4dcded3f.png)
Product image not there and product data is also not there

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser Chrome
 - Version [Google Chrome 106.0.5249.91]

**Smartphone (please complete the following information):**
 - Device: [Oppo A57]
 - OS: [ColorOs]
 - Browser [Chrome]

**Additional context**

**Comment by Rose1845** [comment]
Will work on it

**Comment by forinda** [comment]
Working on a component
Gettting `props` is different from `component state`

eg
```jsx
const Singlepoduct=()=>{
return <>Something</>
}

const X=()=>{
return <><SingleProduct/></> // Works well
}
```
With props you have to supply all the props
```jsx
const Singlepoduct=(props:{title:string})=>{
return <>Something from {props.title}</>
}

const X=()=>{
return <><SingleProduct/></> // Will not work unless you supply the props 
}

const Y=()=>{
const [title,setTitle]=React.useState<string>('Some title')
return <><SingleProduct title={title}/></> // Will work
}
```

So the issue was you were supplying props from the page level instead of setting the item as the product.
